### ISSUE TITLE
Updating u-boot while running OpenWRT

### ISSUE THREAD

**Issue by erayrafet** [hkint/xiaomi-ax3000t-immortalwrt-hanwckf-firmware-build#3]
How am I supposed to update to newer uboot releases once available? I already have OpenWRT running so `mtd write /tmp/mt7981_ax3000t-fip-fixed-parts-multi-layout.bin FIP` would be enough, correct?

**Comment by hkint** [comment]
@erayrafet 

In theory, yes! 
You should be able to write U-Boot to the FIP partition using the `mtd` command. 

This repository is just for compiling, though. For more information about U-Boot, check out the source repository -- https://github.com/hanwckf/immortalwrt-mt798x

**Comment by erayrafet** [comment]
@hkint Thanks for the swift reply!
I'll give this ago when the next release comes out. I took partition backups and I have UART ready to go in case I need to recover. OpenWRT's bootloaders either result in a boot loop or break wifi alltogether. And lack that fancy update/recovery web UI. I'll reopen the issue if I face an issue.
Cheers!

**Comment by erayrafet** [comment]
![image](https://github.com/user-attachments/assets/f7aa44f7-2072-4cfc-9fed-4b8bd8428bf3)

@hkint No luck.

**Comment by erayrafet** [comment]
I had to install `kmod-mtd-rw`

`insmod /lib/modules/$(uname -r)/mtd-rw.ko i_want_a_brick=1`

And the mtd write command worked.

**Comment by hkint** [comment]
@erayrafet 
That’s great! 
I just saw the notification and was about to reply.

**Comment by erayrafet** [comment]
> @erayrafet That’s great! I just saw the notification and was about to reply.

What's new with this update?

**Comment by hkint** [comment]
Sorry, I might not have expressed this repo clearly. 

The release here is just a scheduled monthly build, and there might not be any updates, as it all depends on the upstream. 

If you're interested, you can check the corresponding commit history here: https://github.com/hanwckf/bl-mt798x/commits/master/
