### ISSUE TITLE
如何修改参数以编译AX3000T-an8855？

### ISSUE THREAD

**Issue by WANGXianru-PolyU** [hkint/xiaomi-ax3000t-immortalwrt-hanwckf-firmware-build#4]
请问需要修改哪些参数，才能将编译对象换为mt7981-xiaomi-ax3000t-an8855？
hanwckf大佬的更新日志：
https://github.com/hanwckf/immortalwrt-mt798x/commit/d6138f353da41d735c0610e040383470b7faac6d
https://github.com/hanwckf/bl-mt798x/commit/880d7df742396c10f29441ec75a34bd8a098cc4e

**Comment by hkint** [comment]
理论上更新 `.config` 的 Target Device 即可。
H大 那边 https://github.com/hanwckf/immortalwrt-mt798x/issues/335#issuecomment-2468564635 U-Boot 是可以了，固件似乎还得等等。
我手头上没有an8855 的设备了，等有时间再弄

**Comment by WANGXianru-PolyU** [comment]
> 理论上更新 `.config` 的 Target Device 即可。 H大 那边 [hanwckf/immortalwrt-mt798x#335 (comment)](https://github.com/hanwckf/immortalwrt-mt798x/issues/335#issuecomment-2468564635) U-Boot 是可以了，固件似乎还得等等。 我手头上没有an8855 的设备了，等有时间再弄

H大在issue里说“固件已经适配好了，测试正常”。我fork本项目并云编译，遇到了一样的错误：
https://github.com/hkint/xiaomi-ax3000t-immortalwrt-hanwckf-firmware-build/actions/runs/11798310347
期待您有时间的话修复一下

**Comment by hkint** [comment]
@WANGXianru-PolyU 构建成功，有需要可以先测试下最新 release

**Comment by WANGXianru-PolyU** [comment]
大佬，我想再问一下，编译出来的带“stock”的固件是什么意思？网上搜索也没找到相关信息

**Comment by WANGXianru-PolyU** [comment]
> @WANGXianru-PolyU 构建成功，有需要可以先测试下最新 release


大佬，我想再问一下，编译出来的带“stock”的固件是什么意思？网上搜索也没找到相关信息

**Comment by hkint** [comment]
参考：https://www.right.com.cn/forum/thread-8395248-1-1.html
